//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonation
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class BloodDonationHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BloodDonationHistory()
        {
            //this.DiseasesResults = new HashSet<DiseasesResult>();
        }

        public BloodDonationHistory(string donorCNP, string donatedForCNP, Guid donationID, DateTime date, int quantity)
        {
            DonorCNP = donorCNP;
            DonatedForCNP = donatedForCNP;
            DonationID = donationID;
            Date = date;
            Quantity = quantity;
        }

        public BloodDonationHistory(string donorCNP, string donatedForCNP, Guid donationID)
        {
            DonorCNP = donorCNP;
            DonatedForCNP = donatedForCNP;
            DonationID = donationID;
            Quantity = 0;
        }

        [DataMember(Name = "DonorCNP")]
        public string DonorCNP { get; set; }

        [DataMember(Name = "DonatedForCNP")]
        public string DonatedForCNP { get; set; }

        [DataMember(Name = "DonationID")]
        public System.Guid DonationID { get; set; }

        [DataMember(Name = "Date")]
        public Nullable<System.DateTime> Date { get; set; }

        [DataMember(Name = "Quantity")]
        public Nullable<int> Quantity { get; set; }
    
        //public virtual Donor Donor { get; set; }
        //public virtual Patient Patient { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DiseasesResult> DiseasesResults { get; set; }

        override public string ToString()
        {
            return DonorCNP + " - " + DonatedForCNP + " - " + Date + " - " + Quantity;
        }

        
    }
}
