//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonation
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class DiseasesResult
    {
        public DiseasesResult()
        {

        }

        public DiseasesResult(Guid diseaseID, Guid donationID)
        {
            DiseaseID = diseaseID;
            DonationID = donationID;
        }

        [DataMember(Name = "DiseaseID")]
        public System.Guid DiseaseID { get; set; }

        [DataMember(Name = "DonationID")]
        public System.Guid DonationID { get; set; }

        [DataMember(Name = "JustForModels")]
        public Nullable<int> JustForModels { get; set; }
    
        //public virtual BloodDonationHistory BloodDonationHistory { get; set; }
        //public virtual Disease Disease { get; set; }
    }
}
