//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonation
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Donor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donor()
        {
            //this.BloodDonationHistories = new HashSet<BloodDonationHistory>();
            //this.Notifications = new HashSet<Notification>();
        }

        public Donor(string CNP, string firstName, string lastName, DateTime date, Guid addressID, Guid residenceID, Guid? bloodtypeID)
        {
            this.CNP = CNP;
            this.FirstName = firstName;
            this.LastName = lastName;
            this.DateOfBirth = date;
            this.AddressID = addressID;
            this.ResidenceID = residenceID;
            this.BloodTypeID = bloodtypeID;
        }

        [DataMember(Name = "CNP")]
        public string CNP { get; set; }

        [DataMember(Name = "FirstName")]
        public string FirstName { get; set; }

        [DataMember(Name = "LastName")]
        public string LastName { get; set; }

        [DataMember(Name = "DateOfBirth")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }

        [DataMember(Name = "ResidenceID")]
        public Nullable<System.Guid> ResidenceID { get; set; }

        [DataMember(Name = "AddressID")]
        public Nullable<System.Guid> AddressID { get; set; }

        [DataMember(Name = "BloodTypeID")]
        public Nullable<System.Guid> BloodTypeID { get; set; }
    
        //public virtual Address Address { get; set; }
        //public virtual Address Address1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<BloodDonationHistory> BloodDonationHistories { get; set; }
        //public virtual BloodType BloodType { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Notification> Notifications { get; set; }
    }
}
