//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonation
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Request
    {
        [DataMember(Name = "PatientCNP")]
        public string PatientCNP { get; set; }

        [DataMember(Name = "DoctorCNP")]
        public string DoctorCNP { get; set; }

        [DataMember(Name = "BloodBankID")]
        public Nullable<System.Guid> BloodBankID { get; set; }

        [DataMember(Name = "Priority")]
        public Nullable<int> Priority { get; set; }

        [DataMember(Name = "RedBloodCellsQuantity")]
        public Nullable<int> RedBloodCellsQuantity { get; set; }

        [DataMember(Name = "PlasmaQuantity")]
        public Nullable<int> PlasmaQuantity { get; set; }

        [DataMember(Name = "TrombocitesQuantity")]
        public Nullable<int> TrombocitesQuantity { get; set; }

        [DataMember(Name = "IsCompleted")]
        public Nullable<bool> IsCompleted { get; set; }

        public Request() { }

        public Request(string patientCNP, string doctorCNP, Guid? bankID, int? priority, int? redq, int? plasmaq, int? trombocitesq, bool? completed)
        {
            this.PatientCNP = patientCNP;
            this.DoctorCNP = doctorCNP;
            this.BloodBankID = bankID;
            this.Priority = priority;
            this.RedBloodCellsQuantity = redq;
            this.PlasmaQuantity = plasmaq;
            this.TrombocitesQuantity = trombocitesq;
            this.IsCompleted = completed;
        }
    
        //public virtual BloodBank BloodBank { get; set; }
        //public virtual Doctor Doctor { get; set; }
        //public virtual Patient Patient { get; set; }
    }
}
